# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.8.5


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [2]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 29 ms
Wall time: 1.59 s


### Exercício 2

In [3]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5:8] = 0
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [5]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [7]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Imprima os elementos da terceira linha da matriz
arr2d[2]

array([7, 8, 9])

In [9]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

### Exercício 5

In [10]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [12]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [13]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [14]:
resultado = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [15]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = np.arange(10)
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [17]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [18]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [19]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [20]:
data = resp.json()
data[0]['title']

'REF/TYP: Block._slice and related'

In [21]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    45254                  REF/TYP: Block._slice and related   
1    45253  ENH: Bring over Microsoft typing stubs as star...   
2    45252  ENH: Add set of tests to type check the public...   
3    45251           DOC CLN: use ``color`` shared doc string   
4    45250       BUG: mypy complaints on ChainMap, FrozenList   
5    45249  BUG: Unexpected behavioral change, NaN support...   
6    45248  BUG: `DataFrame.groupby` silently ignores `as_...   
7    45246            TYP: Add types for excel writer classes   
8    45245  API: Consistency between DataFrame, MultiIndex...   
9    45244                   TYP: Ignore numpy related issues   
10   45243  BUG: dataframe transform to dict , then accura...   
11   45242                      CLN/PERF: avoid double-checks   
12   45241         BUG: frame.iloc[i] with a single EA column   
13   45240  BUG: pd.testing.assert_series_equal has proble...   
14   45237           DOC: Improve doc summaries in series.rst   
15   45236  PERF: DataFrame.duplicated with subset= for 1 ...   
16   45235  DOC: Convert code-block to ipython block in io...   
17   45234                                 REF: dtypes.astype   
18   45232  BUG: Series.__setitem__ positional raising Val...   
19   45231  BUG: 1.4.0rc1 Error vectorizing grouping aggre...   
20   45230  BUG: 1.4.0rc1 AssertionError when reset_index ...   
21   45228  DOC: comprehensive example of `Styler.to_latex...   
22   45227  BUG: raise on wrong keyword arguments in Timed...   
23   45224  BUG: index level of Series dropped if not cont...   
24   45223                                           RLS: 1.5   
25   45222  BUG: value counts with mixed NaNs is oddly ren...   
26   45221  BUG: Fix lost precision when reading from Orac...   
27   45219  MISC: Check that min versions are aligned in C...   
28   45218  REF: share Categorical._repr_categories and Ca...   
29   45217  Adding unixtime property to Timestamp and Date...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
2   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
3                                                  []  open  
4   [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
5   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
6   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
7                                                  []  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
11                                                 []  open  
12  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
14  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
15  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
16  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
17                                                 []  open  
18                                                 []  open  
19  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21                                                 []  open  
22                                                 []  open  
23  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
24  [{'id': 131473665, 'node_id': 'MDU6TGFiZWwxMzE...  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26                                                 []  open  
27  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29                                                 []  open

### Exercício 10

In [22]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [23]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [24]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [25]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>